### ISSUE TITLE
Converting milliseconds to desired time format

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [be-codified/swimCoachStopwatch#12]
We need a pure function which will convert given milliseconds to desired time format.
Proposed name: convertMillisecondsToTimeFormat

Input:
- milliseconds (number, required, e.g. 24897)
- time format (string, required)
  - a) 's'
  - b) 's:ms'
  - c) 'm:s:ms'
- hasLeadingZeros (boolean, required)

Output can be:

a) 4 (measured in seconds, no leading zero) - this will be mainly used for countdown
b) 03:12 (measured in seconds:milliseconds, with leading zeros)
b) 05:38:89 (measured in minutes:seconds:milliseconds, with leading zeros)

Special cases:

Consider if amount of milliseconds goes above 1h. In this case output should be:
03:58:87 and not 01:03:58:87 (cutting down hour part, minutes part do not go above 59, they start from 00)

Note:

When adding leading zeros, perhaps this could be done with a new pure function.

**Comment by zgavin1** [comment]
Hi Ziga, here's a jsfiddle showing that momentjs would be a good library for this https://jsfiddle.net/zgavin1/96bxjtr5/

**Comment by ZigaVukcevicDev** [comment]
@zgavin1 oh, great. Thank you for the effort.
